services:
  hankang_next:
    container_name: hankang_next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/hankang_next
    working_dir: /usr/src/hankang_next
    networks:
      - client-network
    command: bash -c "yarn && yarn run build && yarn run start"
networks:
  client-network:
    driver: bridge
